language: elixir
elixir:
  - 1.0.5
otp_release:
  - 17.4
services:
  - mysql
sudo: false # to use faster container based build environment
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
script:
  - mix test
notifications:
  recipients:
    - jonhkr@gmail.com